# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: npm ci
      - run: npm test

#  publish-npm:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#        with:
#          node-version: 13
#          registry-url: https://registry.npmjs.org/
#      - run: npm ci
#      - run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13
          registry-url: https://npm.pkg.github.com/
          scope: '@flyingeek'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Build application
        run: npm run build_with_wmo
      - name: upload lidojs.js
        uses: actions-github/upload-to-release@master
        with:
          file: './dist/lidojs.js'
          type: 'text/javascript'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload lidojs.min.js
        uses: actions-github/upload-to-release@master
        with:
          file: './dist/lidojs.min.js'
          type: 'text/javascript'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload lidojs.var.min.js
        uses: actions-github/upload-to-release@master
        with:
          file: './dist/lidojs.var.min.js'
          type: 'text/javascript'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload wmo.json
        uses: actions-github/upload-to-release@master
        with:
          file: './dist/wmo.json'
          type: 'application/json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
